# Generated by Django 3.2.25 on 2024-04-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=125)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pages', models.IntegerField()),
                ('ebooks', models.FileField(upload_to='')),
            ],
        ),
    ]
