# Generated by Django 3.2.25 on 2024-05-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20240501_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
