# Generated by Django 3.2.25 on 2024-05-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_bookmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='ebooks',
            field=models.FileField(upload_to='ebooks/'),
        ),
    ]
