# Generated by Django 3.2.25 on 2024-05-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_alter_bookmodel_ebook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='ebooks',
            new_name='ebook',
        ),
    ]
