# Generated by Django 5.0.3 on 2024-05-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_rename_ebook_bookmodel_ebooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('activ', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'code',
                'verbose_name_plural': 'code',
            },
        ),
    ]
