# Generated by Django 5.0.3 on 2024-05-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_useremail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useremail',
            old_name='activ',
            new_name='is_active',
        ),
    ]
