# Generated by Django 3.2.25 on 2024-05-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_rename_activ_useremail_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmail',
        ),
    ]
